language: java

jdk:
  - oraclejdk8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test jacoco:report

after_success:
  - mvn coveralls:report
